name: Advanced Browser Trigger
on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run Puppeteer Script
        env:
          BROWSERLESS_KEY: ${{ secrets.BROWSERLESS_KEY }}
        run: |
          npm install puppeteer
          node -e "
          const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.connect({
              browserWSEndpoint: `wss://chrome.browserless.io?token=${process.env.BROWSERLESS_KEY}`
            });
            const page = await browser.newPage();
            await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64)');
            await page.goto('https://dailyusa.rf.gd/?wp_automatic=cron', {
              waitUntil: 'networkidle0',
              timeout: 30000
            });
            await page.waitForTimeout(5000);
            await browser.close();
          })();"
