name: Trigger WP Automatic Cron
on:
  schedule:
    - cron: '*/20 * * * *'  # Every 20 minutes
  workflow_dispatch:  # Enable manual runs

jobs:
  trigger-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cron
        run: |
          curl -s -k --fail \
          -A "GitHub-Actions-Cron" \
          "https://dailyusa.rf.gd/?wp_automatic=cron"
