name: Real Browser Cron Trigger
on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:        # Allow manual runs

jobs:
  trigger-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger via Real Browser
        env:
          BROWSERLESS_KEY: ${{ secrets.BROWSERLESS_KEY }}  # Add your key in repo Settings > Secrets
        run: |
          curl -X POST \
          "https://chrome.browserless.io/content?token=${BROWSERLESS_KEY}" \
          -H 'Content-Type: application/json' \
          -d '{
            "url": "https://dailyusa.rf.gd/?wp_automatic_cron",
            "waitForTimeout": 5000,
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
          }'
