name: Trigger WP Automatic Cron
on:
  schedule:
    - cron: '*/20 * * * *'  # Runs every 20 minutes
  workflow_dispatch:        # Allows manual triggers

jobs:
  call-cron:
    runs-on: ubuntu-latest
  steps:
  - name: Trigger WP Cron via Proxy
    run: |
      curl -s -A "Mozilla/5.0" \
      "https://corsproxy.io/?https://dailyusa.rf.gd/?wp_automatic=cron"
