name: Bypass InfinityFree Anti-Bot
on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:

jobs:
  trigger-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Solve Anti-Bot Challenge
        run: |
          # Step 1: First request to get cookies
          COOKIE=$(curl -s -k -i "https://dailyusa.rf.gd/?wp_automatic=cron" | 
                   grep -i 'set-cookie' | awk '{print $2}' | tr -d ';')

          # Step 2: Use cookie in second request
          curl -s -k -b "$COOKIE" -A "Mozilla/5.0" \
          "https://dailyusa.rf.gd/?wp_automatic=cron&t=$(date +%s)"
          
          echo "Cron bypass attempted at $(date)"
