name: WP Automatic Cron
on:
  schedule:
    - cron: '*/20 * * * *'  # Every 20 minutes
  workflow_dispatch:         # Allow manual runs

jobs:
  trigger-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cron
        run: |
          # Try direct (with SSL ignore)
          curl -s -k -A "Mozilla/5.0" \
          "https://dailyusa.rf.gd/?wp_automatic=cron" || \
          
          # Fallback to proxy if direct fails
          curl -s -A "Mozilla/5.0" \
          "https://corsproxy.io/?https://dailyusa.rf.gd/?wp_automatic=cron"
