name: Trigger WP Automatic Cron
on:
  schedule:
    - cron: '*/20 * * * *'  # Runs every 20 minutes
  workflow_dispatch:        # Allows manual triggers

jobs:
  call-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Cron URL
        run: |
          curl -s -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
          "https://dailyusa.rf.gd/?wp_automatic=cron"
